#!/usr/bin/env node
/**
 * Build the static site data bundle for GitHub Pages.
 * Reads verified data files + re-exports the engine's computed results
 * into src/data/site-data.js (committed; the Pages site is fully static).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));
// Forward-loop artifacts appear once the networked collector has run (ROADMAP R1-R4).
// The bundle must stay small: summaries only, never the full raw captures.
const readIfExists = (p) => { try { return read(p); } catch { return null; } };

const snapshot = read('data/kalshi/snapshot-2026-09-18.json');
const sources = read('data/sources/master.json');
const outcomes = read('data/outcomes/verified-outcomes.json');
const polls = read('data/polls/verified-polls.json');
const backtests = read('data/backtest-results.json');
const contest = read('data/contest-results.json');
// Both toolchains publish irregularities; the site shows the complete list.
const irregularitiesNode = read('data/irregularities.json');
const irregularitiesPython = read('data/irregularities-python-track.json');
const irregularities = {
  title: 'Irregularities & discrepancies — combined (both toolchains)',
  method: 'Node-track items live in data/irregularities.json; Python-track items (13-22) are transcribed verbatim from the IRREGULARITIES.md table into data/irregularities-python-track.json. Combined here in id order for the site.',
  items: [
    ...irregularitiesNode.items.map((i) => ({ ...i, track: 'node' })),
    ...irregularitiesPython.items,
  ].sort((a, b) => a.id - b.id),
};
const roadmap = read('data/roadmap.json');

// --- ROADMAP R1-R4 forward-loop artifacts (null until the networked collector runs) ---
const senate2024Full = readIfExists('data/senate-2024-backtest.json');
const senate2024 = senate2024Full && {
  generatedAt: senate2024Full.generatedAt,
  inputs: senate2024Full.inputs,
  note: senate2024Full.note,
  nMarkets: senate2024Full.nMarkets,
  settlementCrossCheck: senate2024Full.settlementCrossCheck,
  aggregate: senate2024Full.aggregate,
  aggregateByBandT7: senate2024Full.aggregateByBandT7,
  holdOfficialWinners: senate2024Full.holdOfficialWinners,
  universeCoverage: senate2024Full.universeCoverage,
  captureErrors: senate2024Full.captureErrors,
  markets: (senate2024Full.markets || []).map((m) => ({
    ticker: m.ticker, state: m.state, side: m.side, title: m.title,
    result: m.result, officialWinner: m.officialWinner, officialWinnerParty: m.officialWinnerParty,
    crossCheck: m.crossCheck, bandT7: m.bandT7, p7: m.p7, volume: m.volume,
    nTradeBars: m.nTradeBars, leadTimes: m.leadTimes,
    series: (m.dailySeries || []).map((p) => ({ date: p.date, p: p.p })),
  })),
};
const calibration = readIfExists('data/calibration-2026.json');
const polls2026 = readIfExists('data/polls/polls-2026-series.json');
const universeOpen = readIfExists('data/kalshi/forward/universe-open.json');
const universeSummary = universeOpen && {
  capturedFrom: universeOpen.capturedFrom,
  capturedAt: universeOpen.capturedAt,
  date: universeOpen.date,
  count: universeOpen.count,
  seriesQueried: universeOpen.seriesQueried,
  top: [...(universeOpen.markets || [])]
    .sort((a, b) => Number(b.vol || 0) - Number(a.vol || 0))
    .slice(0, 15)
    .map((m) => ({ ticker: m.ticker, event: m.event_ticker, series: m.series, sub: m.sub, bid: m.bid, ask: m.ask, vol: m.vol, oi: m.oi, close_time: m.close_time })),
};

// 538 national 2024 average series (downsampled to weekly + key dates for the chart)
import { loadNationalAverages, nationalMargin } from '../src/poll-backtest.js';
const byDate = loadNationalAverages(join(ROOT, 'data/polls/538-national-averages.csv'));
const allDates = [...byDate.keys()].sort();
const keySet = new Set(['2024-03-01', '2024-06-30', '2024-07-21', '2024-08-05', '2024-09-12']);
const weekly = allDates.filter((d, i) => i % 7 === 0 || keySet.has(d));
const pollSeries = weekly.map((d) => ({ date: d, margin: nationalMargin(byDate, d) })).filter((p) => p.margin !== null);

const bundle = {
  generatedAt: new Date().toISOString(),
  snapshot,
  sources,
  outcomes,
  polls,
  backtests,
  contest,
  irregularities,
  roadmap,
  pollSeries2024: pollSeries,
  senate2024,        // ROADMAP R2 (null until the networked capture + backtest run)
  calibration,       // ROADMAP R3 (null until the forward collector runs)
  polls2026,         // ROADMAP R4
  universeSummary,   // ROADMAP R1 (latest open-universe snapshot summary)
  meta: {
    project: 'Elections — collect, analyze, project & estimate',
    updated: '2026-09-19',
    repo: 'https://github.com/buffedlizard55-lab/Elections',
  },
};

const dir = join(ROOT, 'src/data');
mkdirSync(dir, { recursive: true });
const js = '// GENERATED by scripts/build-site.mjs — do not edit by hand.\nwindow.SITE_DATA = ' + JSON.stringify(bundle) + ';\n';
writeFileSync(join(dir, 'site-data.js'), js);
console.log(`wrote src/data/site-data.js (${(js.length / 1024).toFixed(0)} KB)`);
