#!/usr/bin/env node
/**
 * Build the static site data bundle for GitHub Pages.
 * Reads verified data files + re-exports the engine's computed results
 * into src/data/site-data.js (committed; the Pages site is fully static).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));

const snapshot = read('data/kalshi/snapshot-2026-09-18.json');
const sources = read('data/sources/master.json');
const outcomes = read('data/outcomes/verified-outcomes.json');
const polls = read('data/polls/verified-polls.json');
const backtests = read('data/backtest-results.json');
const contest = read('data/contest-results.json');
// Both toolchains publish irregularities; the site shows the complete list.
const irregularitiesNode = read('data/irregularities.json');
const irregularitiesPython = read('data/irregularities-python-track.json');
const irregularities = {
  title: 'Irregularities & discrepancies — combined (both toolchains)',
  method: 'Node-track items live in data/irregularities.json; Python-track items (13-22) are transcribed verbatim from the IRREGULARITIES.md table into data/irregularities-python-track.json. Combined here in id order for the site.',
  items: [
    ...irregularitiesNode.items.map((i) => ({ ...i, track: 'node' })),
    ...irregularitiesPython.items,
  ].sort((a, b) => a.id - b.id),
};
const roadmap = read('data/roadmap.json');

// 538 national 2024 average series (downsampled to weekly + key dates for the chart)
import { loadNationalAverages, nationalMargin } from '../src/poll-backtest.js';
const byDate = loadNationalAverages(join(ROOT, 'data/polls/538-national-averages.csv'));
const allDates = [...byDate.keys()].sort();
const keySet = new Set(['2024-03-01', '2024-06-30', '2024-07-21', '2024-08-05', '2024-09-12']);
const weekly = allDates.filter((d, i) => i % 7 === 0 || keySet.has(d));
const pollSeries = weekly.map((d) => ({ date: d, margin: nationalMargin(byDate, d) })).filter((p) => p.margin !== null);

const bundle = {
  generatedAt: new Date().toISOString(),
  snapshot,
  sources,
  outcomes,
  polls,
  backtests,
  contest,
  irregularities,
  roadmap,
  pollSeries2024: pollSeries,
  meta: {
    project: 'Elections — collect, analyze, project & estimate',
    updated: '2026-09-18',
    repo: 'https://github.com/buffedlizard55-lab/Elections',
  },
};

const dir = join(ROOT, 'src/data');
mkdirSync(dir, { recursive: true });
const js = '// GENERATED by scripts/build-site.mjs — do not edit by hand.\nwindow.SITE_DATA = ' + JSON.stringify(bundle) + ';\n';
writeFileSync(join(dir, 'site-data.js'), js);
console.log(`wrote src/data/site-data.js (${(js.length / 1024).toFixed(0)} KB)`);
