#!/usr/bin/env node
/**
 * Generates ROADMAP.md from data/roadmap.json (the machine-readable twin).
 * Run: node scripts/gen-roadmap.mjs   (also part of `npm run pipeline`)
 * The markdown is a pure function of the JSON, so the two cannot drift.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const rm = JSON.parse(readFileSync(join(ROOT, 'data/roadmap.json'), 'utf8'));

const lines = [];
lines.push('# ROADMAP — remaining work & limitations', '');
lines.push(`Machine-readable twin: \`data/roadmap.json\` (updated ${rm.updated}). ${rm.limit} ${rm.source[0].toUpperCase()}${rm.source.slice(1)}.`, '');
lines.push('_Generated by `scripts/gen-roadmap.mjs` — edit `data/roadmap.json`, not this file._', '');
lines.push('## Status board', '', '| Item | Status | Title |', '|---|---|---|');
for (const r of rm.items) lines.push(`| ${r.id} | ${r.status} | ${r.title} |`);
lines.push('', '## Items', '');
for (const r of rm.items) {
  lines.push(`### ${r.id} · ${r.title} — P${r.priority} — **${r.status}**`);
  lines.push(r.detail);
  lines.push(`**Why:** ${r.why}`, '');
}
lines.push('## Current limitations', '');
for (const l of rm.limitations) lines.push(`- ${l}`);
lines.push('', 'See also `LIMITATIONS.md` (narrative) and `NEXT_SESSION.md` (start-here checklist).', '');

writeFileSync(join(ROOT, 'ROADMAP.md'), lines.join('\n'));
console.log(`wrote ROADMAP.md (${rm.items.length} items, ${rm.limitations.length} limitations)`);
